// Dinosaur-themed word list for Paleo Pictionary
// Categories: dinosaurs, prehistoric life, actions, places, objects

export const PICTIONARY_WORDS: string[] = [
  // Dinosaurs
  "T. Rex",
  "Velociraptor",
  "Triceratops",
  "Stegosaurus",
  "Brontosaurus",
  "Pterodactyl",
  "Ankylosaurus",
  "Spinosaurus",
  "Diplodocus",
  "Allosaurus",
  "Iguanodon",
  "Parasaurolophus",
  "Pachycephalosaurus",
  "Compsognathus",
  "Dilophosaurus",
  "Brachiosaurus",
  "Carnotaurus",
  "Gallimimus",
  "Oviraptor",
  "Deinonychus",
  "Mosasaurus",
  "Plesiosaurus",
  "Archaeopteryx",
  "Megalodon",
  "Dimorphodon",
  
  // Prehistoric creatures (non-dinosaurs)
  "Woolly Mammoth",
  "Saber-tooth Tiger",
  "Giant Sloth",
  "Dodo Bird",
  "Trilobite",
  "Ammonite",
  "Giant Scorpion",
  "Pteranodon",
  
  // Body parts
  "Tail",
  "Claw",
  "Fang",
  "Horn",
  "Spine",
  "Wing",
  "Beak",
  "Feathers",
  "Scales",
  "Teeth",
  "Skull",
  "Skeleton",
  "Footprint",
  
  // Places
  "Volcano",
  "Swamp",
  "Jungle",
  "Cave",
  "Nest",
  "Lake",
  "Desert",
  "Mountain",
  "Forest",
  "River",
  "Island",
  "Beach",
  "Tar Pit",
  
  // Objects
  "Fossil",
  "Egg",
  "Bone",
  "Rock",
  "Tree",
  "Fern",
  "Meteor",
  "Amber",
  "Footprints",
  "Museum",
  "Skeleton",
  "Excavation",
  "Brush",
  "Hammer",
  
  // Actions
  "Roaring",
  "Hunting",
  "Running",
  "Flying",
  "Swimming",
  "Hatching",
  "Eating",
  "Fighting",
  "Sleeping",
  "Stomping",
  "Biting",
  "Chasing",
  "Hiding",
  "Digging",
  "Nesting",
  
  // Concepts
  "Extinction",
  "Evolution",
  "Jurassic",
  "Cretaceous",
  "Prehistoric",
  "Carnivore",
  "Herbivore",
  "Pack",
  "Herd",
  "Migration",
  "Predator",
  "Prey",
  "Apex",
  "Fossil Fuel",
  "Ice Age",
  
  // Fun combos
  "Dino Egg",
  "Fossil Hunt",
  "Meteor Strike",
  "Lava Flow",
  "Bone Bed",
  "Tar Trap",
  "Nest Raid",
  "Pack Hunt",
  "Dino Battle",
  "Flying Reptile",
];
